### ISSUE TITLE
Modern emacs does not support :server and :nowait together in make-network-process

### ISSUE THREAD

**Issue by tjb7** [ahungry/geben#51]
issue has also been described in other packages: https://github.com/eschulte/emacs-web-server/issues/8, but also elsewhere.

Fix is simple:
Either remove :nowait (tried) in dbpg.el or set it to nil (I didn't try). 

GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-05-19

**Comment by ghost** [comment]
So, it looks like this issue was fixed in https://github.com/ahungry/geben/commit/f40a67ffc3d30ca39bfc7984b1f3909590594acc 

I ran into this issue as well. Turns out my `package-archive-priorities` was set to `'(("melpa-stable" . 1))`. Changing to `melpa`, `rm -rf ~/.emacs.d/elpa/geben-1.1.1` and reinstalling fixed it for me.

**Comment by tjb7** [comment]
thanks. Sorry should have checked.
