### ISSUE TITLE
Warning (emacs): GEBEN internal error

### ISSUE THREAD

**Issue by teledyn** [ahungry/geben#53]
This appears to be benign, although annoying: I get these messages pumped into the `*Warnings*` buffer that is then brought to focus, with the message followed by a long list of my (laravel) php files and ending in `\.\.\.` 

`Warning (emacs): GEBEN internal error: (wrong-type-argument plistp (:proxy nil :port 9000 :language :php :fileuri "file:///var/html/public/index.php" :source (`_long list of php files_` \.\.\.))`

I'm not very proficient in elisp; what might be the cause of this message and is there some way to get more information?

**Comment by ahungry** [comment]
Strange - says plistp, which seems correct for most of what follows (a property list) - the backslash dots at the end seem odd and may be the problem.  

Given the age of this, I'm going to assume you either figured it out, or have long since moved on.

I didn't see a similar error when testing a minimal sample, and have no way to reproduce your file list, so I'm going to close for now.
